version: "3.1"
services:
    web:
        container_name: webSitejacee
        build: .
        ports: 
            - "3000:3000"
        volumes:
            - ./web:/usr/app
        depends_on:
            - backend
        
    backend:
        container_name: apiJacee
        build: .
        ports:
            - "3333:3333"
        volumes:
            - "./backend:/usr/app"
        
        